<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NLog" Version="6.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="obj\Debug\net8.0\ConsoleApp2.csproj.AssemblyReference.cache" />
    </ItemGroup>

</Project>
